# Generated by Django 5.2.3 on 2025-09-11 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان کیس')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('summary', models.TextField(verbose_name='خلاصه کیس')),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='medium', max_length=10, verbose_name='سطح دشواری')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='برچسب\u200cها')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.casecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'کیس',
                'verbose_name_plural': 'کیس\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'مشاهده'), ('start', 'شروع'), ('complete', 'تکمیل'), ('retry', 'تلاش مجدد')], max_length=20, verbose_name='عمل')),
                ('details', models.TextField(blank=True, null=True, verbose_name='جزئیات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cases.case', verbose_name='کیس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه کیس',
                'verbose_name_plural': 'تاریخچه کیس\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('type', models.CharField(choices=[('multiple_choice', 'چندگزینه\u200cای'), ('true_false', 'درست/غلط'), ('text', 'متنی')], default='multiple_choice', max_length=20, verbose_name='نوع تست')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='cases.case', verbose_name='کیس')),
            ],
            options={
                'verbose_name': 'تست کیس',
                'verbose_name_plural': 'تست\u200cهای کیس',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cases.casetest', verbose_name='تست')),
            ],
            options={
                'verbose_name': 'گزینه تست',
                'verbose_name_plural': 'گزینه\u200cهای تست',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='تصویر')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان اسلاید')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='cases.case', verbose_name='کیس')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام زیردسته\u200cبندی')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cases.casecategory', verbose_name='دسته\u200cبندی اصلی')),
            ],
            options={
                'verbose_name': 'زیردسته\u200cبندی',
                'verbose_name_plural': 'زیردسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.subcategory', verbose_name='زیردسته\u200cبندی'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('score', models.FloatField(default=0.0, verbose_name='امتیاز')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='cases.case', verbose_name='کیس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیشرفت کاربر',
                'verbose_name_plural': 'پیشرفت کاربران',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'case')},
            },
        ),
    ]
