# Generated by Django 5.2.3 on 2025-10-01 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('slug', models.TextField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی کیس',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'db_table': 'cases_casecategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.TextField(blank=True, null=True, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True, verbose_name='پیشینه')),
                ('correct_diagnosis', models.TextField(blank=True, null=True, verbose_name='تشخیص صحیح')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.casecategory')),
            ],
            options={
                'db_table': 'cases_case',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.TextField(blank=True, null=True)),
                ('normal_range', models.TextField(blank=True, null=True)),
                ('lab_result', models.TextField(blank=True, null=True)),
                ('lab_type', models.CharField(max_length=50)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(db_column='case_study_id', on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='cases.case')),
            ],
            options={
                'db_table': 'case_tests',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='cases.case')),
            ],
            options={
                'db_table': 'cases_slide',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cases.casecategory')),
            ],
            options={
                'verbose_name': 'زیردسته\u200cبندی',
                'verbose_name_plural': 'زیردسته\u200cبندی\u200cها',
                'db_table': 'cases_subcategory',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.subcategory'),
        ),
        migrations.CreateModel(
            name='UserObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_text', models.TextField(blank=True, db_column='option_text', null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_observations', to='cases.case')),
                ('case_test', models.ForeignKey(blank=True, db_column='case_test_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cases.labtest')),
            ],
            options={
                'db_table': 'case_options',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('total_cases_completed', models.IntegerField(default=0)),
                ('total_correct_observations', models.IntegerField(default=0)),
                ('total_observations', models.IntegerField(default=0)),
                ('total_correct_diagnoses', models.IntegerField(default=0)),
                ('total_diagnoses', models.IntegerField(default=0)),
                ('average_attempts_per_case', models.FloatField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(db_column='case_study_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='cases.case')),
                ('last_test', models.ForeignKey(blank=True, db_column='last_test_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.labtest')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='case_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_progress',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('cbc', 'CBC'), ('chem', 'Clinical Chemistry'), ('morpho', 'Morphological Changes'), ('other', 'Other Tests'), ('slide', 'Slides')], max_length=100)),
                ('report', models.TextField(blank=True, null=True)),
                ('observations', models.JSONField(blank=True, default=list)),
                ('correct_observations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='cases.case')),
            ],
            options={
                'db_table': 'tests',
                'unique_together': {('case', 'title')},
            },
        ),
    ]
