# Generated by Django 5.2.3 on 2025-07-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='case',
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('CBC', 'CBC'), ('CHEM', 'Clinical Chemistry'), ('OTHER', 'Other Tests'), ('SLIDE', 'Slides')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('reference_range', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('report', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('description', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='cases.case')),
            ],
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
