# Generated by Django 5.2.3 on 2025-09-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان توضیح')),
                ('content', models.TextField(verbose_name='محتوای توضیح')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='cases.case', verbose_name='کیس')),
            ],
            options={
                'verbose_name': 'پاسخ تشریحی',
                'verbose_name_plural': 'پاسخ\u200cهای تشریحی',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='CaseHistory',
        ),
    ]
