# Generated by Django 5.2.3 on 2025-09-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseexplanation_delete_casehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetest',
            name='test_category',
            field=models.CharField(choices=[('CBC', 'CBC'), ('CHEM', 'Clinical Chemistry'), ('MORPHO', 'Morphological Changes'), ('OTHER', 'Other Tests'), ('SLIDE', 'Slides')], default='OTHER', max_length=10, verbose_name='دسته\u200cبندی تست'),
        ),
    ]
