# Generated by Django 5.2.3 on 2025-09-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casetest_test_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='final_diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='تشخیص نهایی'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, verbose_name='حداکثر تلاش\u200cها'),
        ),
    ]
