# Generated by Django 5.2.3 on 2025-09-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_userprogress_final_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='medium', max_length=10, verbose_name='سطح دشواری'),
        ),
    ]
