# Generated by Django 5.2.6 on 2025-09-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_casecategory_case_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
