# Generated by Django 5.2.6 on 2025-09-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_userprofile_subscription_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='correct_observations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='observations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TestOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cases.test')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
