# Generated by Django 5.2.3 on 2025-09-11 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_create_sample_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseexplanation',
            options={'ordering': ['id'], 'verbose_name': 'پاسخ تشریحی', 'verbose_name_plural': 'پاسخ\u200cهای تشریحی'},
        ),
        migrations.RemoveField(
            model_name='caseexplanation',
            name='order_index',
        ),
        migrations.RemoveField(
            model_name='caseexplanation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='final_diagnosis',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='max_attempts',
        ),
        migrations.AddField(
            model_name='caseoption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='slide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.casecategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='case',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.subcategory', verbose_name='زیردسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه کیس'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.TextField(verbose_name='عنوان کیس'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='name',
            field=models.TextField(verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='caseexplanation',
            name='case',
            field=models.ForeignKey(db_column='case_study_id', on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='cases.case', verbose_name='کیس'),
        ),
        migrations.AlterField(
            model_name='caseoption',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='caseoption',
            name='test',
            field=models.ForeignKey(db_column='case_test_id', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cases.casetest', verbose_name='تست'),
        ),
        migrations.AlterField(
            model_name='casetest',
            name='case',
            field=models.ForeignKey(db_column='case_study_id', on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='cases.case', verbose_name='کیس'),
        ),
        migrations.AlterField(
            model_name='casetest',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='casetest',
            name='type',
            field=models.CharField(choices=[('single_choice', 'تک\u200cگزینه\u200cای'), ('multiple_choice', 'چندگزینه\u200cای'), ('text', 'متنی'), ('numeric', 'عددی')], default='single_choice', max_length=50, verbose_name='نوع تست'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='case',
            field=models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='cases.case', verbose_name='کیس'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.CharField(max_length=100, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order_index',
            field=models.IntegerField(verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان اسلاید'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.TextField(verbose_name='نام زیردسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.TextField(blank=True, null=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='تعداد تلاش'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='case',
            field=models.ForeignKey(db_column='case_study_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='cases.case', verbose_name='کیس'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterModelTable(
            name='case',
            table='cases_case',
        ),
        migrations.AlterModelTable(
            name='casecategory',
            table='cases_casecategory',
        ),
        migrations.AlterModelTable(
            name='caseexplanation',
            table='case_explanations',
        ),
        migrations.AlterModelTable(
            name='caseoption',
            table='case_options',
        ),
        migrations.AlterModelTable(
            name='casetest',
            table='case_tests',
        ),
        migrations.AlterModelTable(
            name='slide',
            table='cases_slide',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_categories',
        ),
        migrations.AlterModelTable(
            name='userprogress',
            table='user_progress',
        ),
    ]
