# Generated by Django 5.2.3 on 2025-09-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_caseexplanation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseoption',
            name='test_category',
            field=models.CharField(choices=[('CBC', 'CBC'), ('CHEM', 'Clinical Chemistry'), ('MORPHO', 'Morphological Changes'), ('OTHER', 'Other Tests'), ('SLIDE', 'Slides')], default='OTHER', max_length=20, verbose_name='دسته\u200cبندی تست'),
        ),
    ]
