# Generated by Django 5.2.3 on 2025-09-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_caseoption_test_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetest',
            name='test_category',
        ),
    ]
