# Generated by Django 5.2.6 on 2025-09-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_remove_casetest_test_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetest',
            name='lab_name',
            field=models.TextField(blank=True, null=True, verbose_name='نام آزمایش'),
        ),
        migrations.AddField(
            model_name='casetest',
            name='normal_range',
            field=models.TextField(blank=True, null=True, verbose_name='رنج نرمال'),
        ),
        migrations.AddField(
            model_name='casetest',
            name='lab_result',
            field=models.TextField(blank=True, null=True, verbose_name='جواب آزمایش'),
        ),
        migrations.AddField(
            model_name='casetest',
            name='lab_type',
            field=models.CharField(choices=[('CBC', 'CBC'), ('CHEM', 'Clinical Chemistry'), ('OTHER', 'Other Tests')], default='OTHER', max_length=20, verbose_name='نوع آزمایش'),
        ),
    ]
