# Generated by Django 5.2.3 on 2025-09-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_auto_20250911_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseoption',
            options={'ordering': ['order_index', 'id'], 'verbose_name': 'گزینه کیس', 'verbose_name_plural': 'گزینه\u200cهای کیس'},
        ),
        migrations.AlterModelOptions(
            name='casetest',
            options={'ordering': ['order_index', 'id'], 'verbose_name': 'آزمایش کیس', 'verbose_name_plural': 'آزمایش\u200cهای کیس'},
        ),
        migrations.RemoveField(
            model_name='caseoption',
            name='test_category',
        ),
        migrations.RemoveField(
            model_name='casetest',
            name='question',
        ),
        migrations.RemoveField(
            model_name='casetest',
            name='type',
        ),
        migrations.AddField(
            model_name='caseoption',
            name='lab_type',
            field=models.CharField(choices=[('CBC', 'CBC'), ('CHEM', 'Clinical Chemistry'), ('OTHER', 'Other Tests')], default='OTHER', max_length=20, verbose_name='نوع آزمایش'),
        ),
        migrations.AlterField(
            model_name='casetest',
            name='lab_type',
            field=models.CharField(blank=True, choices=[('CBC', 'CBC'), ('CHEM', 'Clinical Chemistry'), ('OTHER', 'Other Tests')], default='OTHER', max_length=20, null=True, verbose_name='نوع آزمایش'),
        ),
    ]
