# Generated by Django 5.2.3 on 2025-09-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_caseoption_options_alter_casetest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetest',
            name='question',
            field=models.TextField(default='N/A', verbose_name='سوال'),
        ),
        migrations.AddField(
            model_name='casetest',
            name='type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('text', 'Text'), ('numeric', 'Numeric')], default='text', max_length=20, verbose_name='نوع سوال'),
        ),
    ]
