# Generated by Django 5.2.3 on 2025-09-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_casetest_question_casetest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetest',
            name='question',
        ),
        migrations.RemoveField(
            model_name='casetest',
            name='type',
        ),
    ]
