# Generated by Django 5.2.3 on 2025-09-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_remove_casetest_question_remove_casetest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseoption',
            name='lab_type',
        ),
    ]
