# Generated by Django 5.2.6 on 2025-09-12 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_remove_caseoption_lab_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseoption',
            name='test',
        ),
        migrations.RemoveField(
            model_name='casetest',
            name='case',
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='casecategory',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی کیس', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.casecategory'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.subcategory'),
        ),
        migrations.AlterField(
            model_name='case',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='case',
            field=models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cases.casecategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='cases_subcategory',
        ),
        migrations.AlterModelTable(
            name='userprogress',
            table=None,
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.TextField(blank=True, null=True)),
                ('normal_range', models.TextField(blank=True, null=True)),
                ('lab_result', models.TextField(blank=True, null=True)),
                ('lab_type', models.CharField(max_length=50)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(db_column='case_study_id', on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='cases.case')),
            ],
            options={
                'db_table': 'case_tests',
            },
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.labtest'),
        ),
        migrations.CreateModel(
            name='UserObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField()),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_observations', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('total_cases_completed', models.IntegerField(default=0)),
                ('total_correct_observations', models.IntegerField(default=0)),
                ('total_observations', models.IntegerField(default=0)),
                ('total_correct_diagnoses', models.IntegerField(default=0)),
                ('total_diagnoses', models.IntegerField(default=0)),
                ('average_attempts_per_case', models.FloatField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CaseExplanation',
        ),
        migrations.DeleteModel(
            name='CaseOption',
        ),
        migrations.DeleteModel(
            name='CaseTest',
        ),
    ]
