# Generated by Django 5.2.6 on 2025-09-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_remove_caseoption_test_remove_casetest_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='correct_diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='تشخیص صحیح'),
        ),
        migrations.AddField(
            model_name='case',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='case',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='پیشینه'),
        ),
    ]
