# Generated by Django 5.2.6 on 2025-09-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_case_correct_diagnosis_case_explanation_case_history'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userobservation',
            table='case_options',
        ),
    ]
