# Generated by Django 5.2.3 on 2025-09-12 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_alter_userobservation_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userobservation',
            old_name='selected_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='userobservation',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userobservation',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userobservation',
            name='selected_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='case',
            field=models.ForeignKey(db_column='case_study_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='last_test',
            field=models.ForeignKey(blank=True, db_column='last_test_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.labtest'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='case_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='userobservation',
            table='user_observations',
        ),
        migrations.AlterModelTable(
            name='userprogress',
            table='user_progress',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('cbc', 'CBC'), ('chem', 'Clinical Chemistry'), ('morpho', 'Morphological Changes'), ('other', 'Other Tests'), ('slide', 'Slides')], max_length=100)),
                ('report', models.TextField(blank=True, null=True)),
                ('observations', models.JSONField(blank=True, default=list)),
                ('correct_observations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='cases.case')),
            ],
            options={
                'db_table': 'tests',
                'unique_together': {('case', 'title')},
            },
        ),
        migrations.AddField(
            model_name='userobservation',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_observations', to='cases.test'),
        ),
        migrations.AlterUniqueTogether(
            name='userobservation',
            unique_together={('user', 'case', 'test')},
        ),
        migrations.CreateModel(
            name='TestOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cases.test')),
            ],
            options={
                'db_table': 'case_options',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='userobservation',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='userobservation',
            name='observation_text',
        ),
    ]
