# Generated by Django 5.2.3 on 2025-09-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_rename_selected_at_userobservation_created_at_and_more'),
    ]

    operations = [
    ]
