# Generated by Django 5.2.3 on 2025-09-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_auto_20250912_2057'),
    ]

    operations = [
    ]
