# Generated by Django 5.2.3 on 2025-09-13 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_auto_20250913_1042'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE case_options ADD COLUMN case_id BIGINT REFERENCES cases_case(id);",
            reverse_sql="ALTER TABLE case_options DROP COLUMN case_id;"
        ),
    ]
