"""
Django settings for vetlms project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-=&rrzi6gyf7eu&j69y$@6$tydpl$h+fqv&oiimhab#f(p$4cd4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    "https://vettest.ir",
    "https://www.vettest.ir",
]

# Vercel deployment settings
ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    '::1',
    'testserver',
    '.vercel.app',
    '130.185.77.50',  # VPS IP
    '.now.sh',
    '.onrender.com',  # Render.com domains
    'heyvoonak-project.vercel.app',  # Your specific domain
    'vetlms.onrender.com',  # Render domain
    'vettest.ir',
    'www.vettest.ir',
]

# در DEBUG=False همه host ها را مجاز کن (فقط برای تست - در production خطرناک است)
if not DEBUG and os.environ.get('ALLOW_ALL_HOSTS', 'False').lower() == 'true':
    ALLOWED_HOSTS = ['*']

# Add your Vercel domain
if os.environ.get('VERCEL_DOMAIN'):
    ALLOWED_HOSTS.append(os.environ.get('VERCEL_DOMAIN'))

# Vercel environment detection
IS_VERCEL = os.environ.get('VERCEL', False)


# Application definition

# Custom User Model
AUTH_USER_MODEL = 'users.CustomUser'

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

INSTALLED_APPS = [
    # Django Core Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Party Apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',

    # Project Apps
    'apps.core',      # Core utilities
    'apps.users',     # User management
    'apps.courses',   # Courses and cases
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cache configuration - کش حداقلی برای سبک‌سازی
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 60,  # کاهش زمان کش از 5 دقیقه به 1 دقیقه
        'OPTIONS': {
            'MAX_ENTRIES': 300,  # کاهش تعداد ورودی‌های کش
        }
    }
}

# تنظیمات Session برای کاهش کش
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # ذخیره در دیتابیس بجای کش
SESSION_COOKIE_AGE = 3600  # 1 ساعت بجای 2 هفته
SESSION_SAVE_EVERY_REQUEST = False  # جلوگیری از ذخیره مداوم session


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for serving static files
   # 'apps.users.middleware.XSSProtectionMiddleware',  # XSS Protection
    #'apps.users.middleware.NoCacheMiddleware',  # Prevent excessive caching
    #'apps.users.middleware.RequestPrivacyMiddleware',  # Privacy middleware
    #'apps.users.middleware.LightNetworkSecurityMiddleware',  # Security middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'apps.users.middleware.RateLimitMiddleware',  # Rate Limiting - DDoS Protection (after auth)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vetlms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # مسیر فایل‌های خطا
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.users.context_processors.cart_context',
            ],
        },
    },
]


WSGI_APPLICATION = 'vetlms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database Configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database selection via environment
DB_ENGINE = os.environ.get('DB_ENGINE', 'django.db.backends.postgresql')

if DB_ENGINE == 'django.db.backends.postgresql':
     DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB_NAME', 'postgres'),
            'USER': os.environ.get('POSTGRES_DB_USER', 'your_user'),
            'PASSWORD': os.environ.get('POSTGRES_DB_PASSWORD', 'your_password'),
            'HOST': os.environ.get('POSTGRES_DB_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }


elif os.environ.get('USE_SQLITE', 'False').lower() == 'true':
    # SQLite (development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # MySQL (default)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'veterinary_cases'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Static files configuration با WhiteNoise
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration - برای serve کردن static files در DEBUG=False
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# اگر مشکل داشت، از این استفاده کنید:
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Vercel deployment
if os.environ.get('VERCEL'):
    # Disable compression for Vercel
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# تنظیمات برای کاهش کش در مرورگر
# XSS Protection Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Additional Security Headers
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'apps' / 'users' / 'static',
    BASE_DIR / 'apps' / 'courses' / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Security Settings - Basic configuration
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# HTTPS Settings
SECURE_SSL_REDIRECT = False  # Set to True in production with HTTPS
# SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# Security Headers - Basic
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Session Security - Basic
# SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_SECURE = not DEBUG
# SESSION_COOKIE_AGE = 3600  # 1 hour
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# SESSION_SAVE_EVERY_REQUEST = True

# CSRF Security - Basic
# CSRF_COOKIE_HTTPONLY = True
# CSRF_COOKIE_SECURE = not DEBUG
# CSRF_USE_SESSIONS = True
# CSRF_COOKIE_AGE = 3600

# X-Frame-Options
# X_FRAME_OPTIONS = 'DENY'

# Additional Security Headers
# SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
# SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'

# Hide server information
# SECURE_HIDE_SERVER_HEADERS = True
# DISALLOWED_USER_AGENTS = []

# Disable DEBUG toolbar and other development tools
if not DEBUG:
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: False,
    }

# Database connection settings
# DATABASES['default']['CONN_MAX_AGE'] = 0  # Disable persistent connections
# PostgreSQL doesn't support init_command like MySQL
if DB_ENGINE == 'django.db.backends.postgresql':
    # PostgreSQL specific options
    DATABASES['default']['OPTIONS'] = {
        # 'sslmode': 'require',
    }
elif DB_ENGINE == 'django.db.backends.mysql':
    # MySQL specific options
    DATABASES['default']['OPTIONS'] = {
        'charset': 'utf8mb4',
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
    }

# Password validation - Basic
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# File upload settings
# FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
# DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
# DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Email backend
# if DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# else:
#     EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'

# Admin settings
# ADMINS = []
# MANAGERS = []

# Logging settings - Basic
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
#             'style': '{',
#         },
#         'simple': {
#             'format': '{levelname} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'simple',
#         },
#         'file': {
#             'class': 'logging.FileHandler',
#             'filename': BASE_DIR / 'logs' / 'django.log',
#             'formatter': 'verbose',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console', 'file'] if DEBUG else ['file'],
#             'level': 'INFO',
#             'propagate': True,
#         },
#         'django.request': {
#             'handlers': ['file'] if not DEBUG else ['console', 'file'],
#             'level': 'ERROR',
#             'propagate': False,
#         },
#     },
# }

# Content Security Policy - Commented out until django-csp is installed
# CSP_DEFAULT_SRC = ("'self'",)
# CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://cdnjs.cloudflare.com")
# CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "https://cdnjs.cloudflare.com")
# CSP_FONT_SRC = ("'self'", "https://cdnjs.cloudflare.com")
# CSP_IMG_SRC = ("'self'", "data:", "https:")

# Logging Configuration - Basic setup
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

# CORS settings for Next.js frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Faraz SMS API Settings
FARAZ_SMS_API_KEY = os.environ.get('FARAZ_SMS_API_KEY', '')
FARAZ_SMS_SENDER_NUMBER = os.environ.get('FARAZ_SMS_SENDER_NUMBER', '')

# کدهای پترن فراز اس‌ام‌اس (از پنل خود دریافت کنید)
FARAZ_PATTERN_VERIFICATION = os.environ.get('FARAZ_PATTERN_VERIFICATION', '')  # پترن کد تایید
FARAZ_PATTERN_PASSWORD_RESET = os.environ.get('FARAZ_PATTERN_PASSWORD_RESET', '')  # پترن بازیابی رمز
FARAZ_PATTERN_PURCHASE = os.environ.get('FARAZ_PATTERN_PURCHASE', '')  # پترن خرید موفق
FARAZ_PATTERN_LOGIN = os.environ.get('FARAZ_PATTERN_LOGIN', '')  # پترن ورود

# ==================================
# تنظیمات زرین‌پال (Zarinpal SDK)
# ==================================
ZARINPAL_MERCHANT_ID = os.environ.get('ZARINPAL_MERCHANT_ID', 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX')
ZARINPAL_ACCESS_TOKEN = os.environ.get('ZARINPAL_ACCESS_TOKEN', '')
ZARINPAL_SANDBOX = os.environ.get('ZARINPAL_SANDBOX', 'True').lower() == 'true'  # True برای تست، False برای واقعی
ZARINPAL_CALLBACK_URL = os.environ.get('ZARINPAL_CALLBACK_URL', 'http://127.0.0.1:8000/payment/callback/')

# ==========================================
# تنظیمات بهینه‌سازی برای سبک‌سازی سایت
# ==========================================

# تنظیمات Template در Development
if DEBUG:
    TEMPLATES[0]['OPTIONS']['debug'] = True
    # Note: APP_DIRS=True already handles template loading
    # Don't set loaders when APP_DIRS is True

# بهینه‌سازی Database Queries
# جلوگیری از persistent connections در محیط توسعه
CONN_MAX_AGE = 0  # بدون connection pooling برای سبک‌تر بودن

# تنظیمات Cookie برای کاهش حجم
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# حذف Middleware های غیرضروری در Production
if not DEBUG:
    # حذف middleware های سنگین
    MIDDLEWARE = [m for m in MIDDLEWARE if 'Debug' not in m]

# تنظیمات Message Framework
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# غیرفعال کردن برخی features برای سبک‌تری
DATA_UPLOAD_MAX_MEMORY_SIZE = 260  # 2.5 MB (کاهش از 10 MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB

# تنظیمات Email (اگر استفاده می‌شود)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # برای توسعه

# جلوگیری از کش زیاد در development
if DEBUG:
    # غیرفعال کردن کامل کش در development
    CACHES['default']['TIMEOUT'] = 0
    
# بهینه‌سازی Static Files
# حذف sourcemaps و فایل‌های اضافی
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# جلوگیری از جمع‌آوری فایل‌های غیرضروری
STATICFILES_IGNORE_PATTERNS = [
    '*.scss',
    '*.sass',
    '*.less',
    '*.coffee',
    '*.ts',
    '*.jsx',
    '*.map',
    'node_modules/*',
    '.git/*',
    '__pycache__/*',
]

# Settings loaded successfully - removed print for Windows compatibility

# (تنظیمات Zarinpal در بالا تعریف شده است)

# =====================================
# KAVENEGAR SMS SETTINGS (جایگزین)
# =====================================
KAVENEGAR_API_KEY = os.environ.get('KAVENEGAR_API_KEY', '')
KAVENEGAR_SENDER_NUMBER = os.environ.get('KAVENEGAR_SENDER_NUMBER', '')
KAVENEGAR_OTP_TEMPLATE = os.environ.get('KAVENEGAR_OTP_TEMPLATE', 'verify')
KAVENEGAR_WELCOME_MESSAGE = 'سلام {username} عزیز! به هی‌ونک خوش آمدید.'
KAVENEGAR_PAYMENT_SUCCESS_MESSAGE = 'پرداخت شما با موفقیت انجام شد. مبلغ: {amount} تومان - کد پیگیری: {ref_id}'
KAVENEGAR_SUBSCRIPTION_RENEWAL_MESSAGE = 'اشتراک {subscription_type} شما تا تاریخ {end_date} تمدید شد.'

# =====================================
# RATE LIMITING SETTINGS 
# =====================================
RATE_LIMIT_ENABLED = True
RATE_LIMIT_MAX_REQUESTS = 500  # حداکثر 500 درخواست عمومی
RATE_LIMIT_WINDOW_SECONDS = 60  # در هر 60 ثانیه
RATE_LIMIT_BLOCK_DURATION = 300  # مسدود کردن برای 5 دقیقه (300 ثانیه)

# اینا رو دقیقاً همینجوری کپی کن تو settings.py
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760   # 10 مگابایت (به جای پیش‌فرض 2.5 مگ)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760   # 10 مگابایت
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000     # جلوگیری از حمله با ۱۰۰۰۰ تا فیلد