# Generated by Django 5.2.3 on 2025-10-03 12:00

from django.db import migrations

# گزینه‌های پیش‌فرض برای CBC
CBC_DEFAULT_OPTIONS = [
    'Polycythemia',
    'No abnormalities', 
    'Mild nonregenerative anemia',
    'Mild regenerative anemia',
    'Neutrophilia',
    'Neutropenia',
    'Lymphopenia',
    'Lymphocytosis',
    'Eosinophilia',
    'Eosinopenia',
    'Monocytosis',
]

# گزینه‌های پیش‌فرض برای CHEM
CHEM_DEFAULT_OPTIONS = [
    'Hypoglycemia',
    'Hyperglycemia',
    'Hypoalbuminemia',
    'Hyperalbuminemia',
    'Hypocalcemia',
    'Hypercalcemia',
    'Hypophosphatemia',
    'Hyperphosphatemia',
    'Hypokalemia',
    'Hyperkalemia',
    'Hyponatremia',
    'Hypernatremia',
    'Hypochloremia',
    'Hyperchloremia',
    'Azotemia',
    'Elevated liver enzymes',
    'Elevated creatinine',
    'Elevated BUN',
    'Elevated cholesterol',
    'Elevated triglycerides',
    'Elevated bilirubin',
    'Elevated alkaline phosphatase',
    'Elevated ALT',
    'Elevated AST',
    'Elevated GGT',
    'Elevated LDH',
    'Elevated CK',
]

# گزینه‌های پیش‌فرض برای MORPHO
MORPHO_DEFAULT_OPTIONS = [
    'Normal morphology',
    'Abnormal RBC morphology',
    'Abnormal WBC morphology',
    'Abnormal platelet morphology',
    'Schistocytes',
    'Spherocytes',
    'Target cells',
    'Burr cells',
    'Acanthocytes',
    'Elliptocytes',
    'Ovalocytes',
    'Teardrop cells',
    'Basophilic stippling',
    'Howell-Jolly bodies',
    'Heinz bodies',
    'Nucleated RBCs',
    'Immature granulocytes',
    'Atypical lymphocytes',
    'Reactive lymphocytes',
    'Plasma cells',
    'Blast cells',
    'Hypersegmented neutrophils',
    'Hyposegmented neutrophils',
    'Toxic granulation',
    'Dohle bodies',
    'Vacuoles',
    'Large platelets',
    'Small platelets',
    'Giant platelets',
    'Platelet clumps',
]

def create_default_options(apps, schema_editor):
    """ایجاد گزینه‌های پیش‌فرض در دیتابیس"""
    Case = apps.get_model('courses', 'Case')
    LabTest = apps.get_model('courses', 'LabTest')
    UserObservation = apps.get_model('courses', 'UserObservation')
    User = apps.get_model('users', 'CustomUser')
    
    # پیدا کردن اولین case
    case = Case.objects.first()
    if not case:
        print("هیچ case ای یافت نشد!")
        return
    
    # پیدا کردن اولین کاربر
    user = User.objects.first()
    if not user:
        print("هیچ کاربری یافت نشد!")
        return
    
    print(f"ایجاد گزینه‌های پیش‌فرض برای case: {case.title}")
    
    # ایجاد CBC test اگر موجود نیست
    cbc_test, created = LabTest.objects.get_or_create(
        case=case,
        lab_type='CBC_DEFAULT',
        defaults={
            'lab_name': 'Complete Blood Count (Default Options)',
            'lab_result': 'N/A',
            'normal_range': 'N/A',
        }
    )
    
    if created:
        print("CBC_DEFAULT test ایجاد شد")
    
    # ایجاد CHEM test اگر موجود نیست
    chem_test, created = LabTest.objects.get_or_create(
        case=case,
        lab_type='CHEM_DEFAULT',
        defaults={
            'lab_name': 'Clinical Chemistry (Default Options)',
            'lab_result': 'N/A',
            'normal_range': 'N/A',
        }
    )
    
    if created:
        print("CHEM_DEFAULT test ایجاد شد")
    
    # ایجاد MORPHO test اگر موجود نیست
    morpho_test, created = LabTest.objects.get_or_create(
        case=case,
        lab_type='MORPHO_DEFAULT',
        defaults={
            'lab_name': 'Morphology (Default Options)',
            'lab_result': 'N/A',
            'normal_range': 'N/A',
        }
    )
    
    if created:
        print("MORPHO_DEFAULT test ایجاد شد")
    
    # ایجاد CBC observations
    print("ایجاد CBC observations...")
    for i, option in enumerate(CBC_DEFAULT_OPTIONS):
        UserObservation.objects.get_or_create(
            case_test=cbc_test,
            observation_text=option,
            defaults={
                'user': user,
                'case': case,
                'is_correct': False,  # پیش‌فرض: غلط
                'order_index': i,
            }
        )
    
    print(f"✅ {len(CBC_DEFAULT_OPTIONS)} CBC observation ایجاد شد")
    
    # ایجاد CHEM observations
    print("ایجاد CHEM observations...")
    for i, option in enumerate(CHEM_DEFAULT_OPTIONS):
        UserObservation.objects.get_or_create(
            case_test=chem_test,
            observation_text=option,
            defaults={
                'user': user,
                'case': case,
                'is_correct': False,  # پیش‌فرض: غلط
                'order_index': i,
            }
        )
    
    print(f"✅ {len(CHEM_DEFAULT_OPTIONS)} CHEM observation ایجاد شد")
    
    # ایجاد MORPHO observations
    print("ایجاد MORPHO observations...")
    for i, option in enumerate(MORPHO_DEFAULT_OPTIONS):
        UserObservation.objects.get_or_create(
            case_test=morpho_test,
            observation_text=option,
            defaults={
                'user': user,
                'case': case,
                'is_correct': False,  # پیش‌فرض: غلط
                'order_index': i,
            }
        )
    
    print(f"✅ {len(MORPHO_DEFAULT_OPTIONS)} MORPHO observation ایجاد شد")
    
    print("🎉 همه گزینه‌های پیش‌فرض ایجاد شدند!")

def reverse_create_default_options(apps, schema_editor):
    """حذف گزینه‌های پیش‌فرض"""
    LabTest = apps.get_model('courses', 'LabTest')
    UserObservation = apps.get_model('courses', 'UserObservation')
    
    # حذف default tests
    LabTest.objects.filter(lab_type__in=['CBC_DEFAULT', 'CHEM_DEFAULT', 'MORPHO_DEFAULT']).delete()
    
    print("گزینه‌های پیش‌فرض حذف شدند")

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_add_user_to_userobservation'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_options, reverse_create_default_options),
    ]
