# Generated by Django 5.2.3 on 2025-10-03 18:20

from django.db import migrations

# گزینه‌های جدید برای CBC (همان قبلی)
CBC_DEFAULT_OPTIONS = [
    'Polycythemia',
    'No abnormalities',
    'Mild nonregenerative anemia',
    'Mild regenerative anemia',
    'Neutrophilia',
    'Neutropenia',
    'Lymphopenia',
    'Lymphocytosis',
    'Eosinophilia',
    'Eosinopenia',
    'Monocytosis',
]

# گزینه‌های جدید برای CHEM
CHEM_DEFAULT_OPTIONS = [
    'No abnormalities',
    'Physiological hypoglycemia',
    'Physiological hyperglycemia',
    'Significative hyperglycemia',
    'Artifactual hypoglycemia',
    'Uremia',
    'Low urea',
    'High liver enzymes',
    'Hyperproteinemia',
    'Hypoproteinemia',
    'Hypoalbuminemia',
    'Hyperglobulinemia',
    'Physiological hypercalcemia',
    'Significant hypercalcemia',
    'Hypocalcemia (hypoalbuminemia)',
    'Significant hypocalcemia',
    'Hyperphosphatemia',
    'Hyperkalemia',
    'Hypokalemia',
    'Hypernatremia',
    'Hyponatremia',
    'Hyperchloremia',
    'Hypochloremia',
    'High anion gap metabolic acidosis',
    'Hyperchloremic metabolic acidosis',
    'Metabolic alkalosis',
    'Mixed acid-base disorder',
]

# گزینه‌های جدید برای MORPHO
MORPHO_DEFAULT_OPTIONS = [
    'No abnormalities',
    'Reactive lymphocytes',
    'Circulating blasts',
    'Spherocytes',
    'Acanthocytes',
    'Keratocytes',
    'Schizocytes',
    'Heinz bodies',
    'Howell-Joly bodies',
    'Autoagglutination',
    'Microcytosis',
    'Megaloblasts',
    'Nucleated red blood cells',
    'Toxic neutrophils',
    'Immature neutrophils',
]

def update_default_options(apps, schema_editor):
    """به‌روزرسانی گزینه‌های پیش‌فرض"""
    LabTest = apps.get_model('courses', 'LabTest')
    UserObservation = apps.get_model('courses', 'UserObservation')
    
    print("🔄 به‌روزرسانی گزینه‌های پیش‌فرض...")
    
    # حذف گزینه‌های قدیمی
    old_default_tests = LabTest.objects.filter(lab_type__in=['CBC_DEFAULT', 'CHEM_DEFAULT', 'MORPHO_DEFAULT'])
    for test in old_default_tests:
        UserObservation.objects.filter(case_test=test).delete()
        test.delete()
        print(f"✅ حذف شد: {test.lab_type}")
    
    # ایجاد گزینه‌های جدید
    case = apps.get_model('courses', 'Case').objects.first()
    user = apps.get_model('users', 'CustomUser').objects.first()
    
    if not case or not user:
        print("❌ Case یا User یافت نشد!")
        return
    
    # ایجاد CBC_DEFAULT جدید
    cbc_test = LabTest.objects.create(
        case=case,
        lab_type='CBC_DEFAULT',
        lab_name='Complete Blood Count (Default Options)',
        lab_result='N/A',
        normal_range='N/A',
    )
    
    for i, option in enumerate(CBC_DEFAULT_OPTIONS):
        UserObservation.objects.create(
            case_test=cbc_test,
            observation_text=option,
            user=user,
            case=case,
            is_correct=False,
            order_index=i,
        )
    print(f"✅ CBC_DEFAULT: {len(CBC_DEFAULT_OPTIONS)} گزینه ایجاد شد")
    
    # ایجاد CHEM_DEFAULT جدید
    chem_test = LabTest.objects.create(
        case=case,
        lab_type='CHEM_DEFAULT',
        lab_name='Clinical Chemistry (Default Options)',
        lab_result='N/A',
        normal_range='N/A',
    )
    
    for i, option in enumerate(CHEM_DEFAULT_OPTIONS):
        UserObservation.objects.create(
            case_test=chem_test,
            observation_text=option,
            user=user,
            case=case,
            is_correct=False,
            order_index=i,
        )
    print(f"✅ CHEM_DEFAULT: {len(CHEM_DEFAULT_OPTIONS)} گزینه ایجاد شد")
    
    # ایجاد MORPHO_DEFAULT جدید
    morpho_test = LabTest.objects.create(
        case=case,
        lab_type='MORPHO_DEFAULT',
        lab_name='Morphology (Default Options)',
        lab_result='N/A',
        normal_range='N/A',
    )
    
    for i, option in enumerate(MORPHO_DEFAULT_OPTIONS):
        UserObservation.objects.create(
            case_test=morpho_test,
            observation_text=option,
            user=user,
            case=case,
            is_correct=False,
            order_index=i,
        )
    print(f"✅ MORPHO_DEFAULT: {len(MORPHO_DEFAULT_OPTIONS)} گزینه ایجاد شد")
    
    print("🎉 به‌روزرسانی کامل شد!")

def reverse_update_default_options(apps, schema_editor):
    """برگشت به حالت قبل"""
    LabTest = apps.get_model('courses', 'LabTest')
    UserObservation = apps.get_model('courses', 'UserObservation')
    
    # حذف گزینه‌های جدید
    new_default_tests = LabTest.objects.filter(lab_type__in=['CBC_DEFAULT', 'CHEM_DEFAULT', 'MORPHO_DEFAULT'])
    for test in new_default_tests:
        UserObservation.objects.filter(case_test=test).delete()
        test.delete()
    
    print("گزینه‌های جدید حذف شدند")

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_create_default_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_default_options, reverse_update_default_options),
    ]
