# Generated by Django 4.2.7 on 2025-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_create_userprofile'),
    ]

    operations = [
        # استفاده از RunSQL برای ایجاد indexes مستقیماً روی جداول واقعی
        migrations.RunSQL(
            # SQL برای ایجاد indexes
            sql=[
                # Indexes برای courses_bookmark
                "CREATE INDEX IF NOT EXISTS courses_boo_user_id_847f49_idx ON courses_bookmark(user_id);",
                "CREATE INDEX IF NOT EXISTS courses_boo_case_id_e29590_idx ON courses_bookmark(case_id);",
                "CREATE INDEX IF NOT EXISTS courses_boo_user_id_7a6f1b_idx ON courses_bookmark(user_id, created_at);",
                
                # Indexes برای courses_case
                "CREATE INDEX IF NOT EXISTS courses_cas_is_publ_74fbc8_idx ON courses_case(is_published, created_at);",
                "CREATE INDEX IF NOT EXISTS courses_cas_categor_460f02_idx ON courses_case(category_id);",
                "CREATE INDEX IF NOT EXISTS courses_cas_sub_cat_230bd9_idx ON courses_case(sub_category_id);",
                "CREATE INDEX IF NOT EXISTS courses_cas_created_d57339_idx ON courses_case(created_at);",
                
                # Indexes برای courses_slide
                "CREATE INDEX IF NOT EXISTS courses_sli_case_id_69ce3c_idx ON courses_slide(case_id);",
                "CREATE INDEX IF NOT EXISTS courses_sli_case_id_de36cb_idx ON courses_slide(case_id, order_index);",
                
                # Indexes برای courses_subcategory
                "CREATE INDEX IF NOT EXISTS courses_sub_categor_d0e11c_idx ON courses_subcategory(category_id);",
                "CREATE INDEX IF NOT EXISTS courses_sub_name_a45ac1_idx ON courses_subcategory(name);",
                
                # Indexes برای case_tests
                "CREATE INDEX IF NOT EXISTS case_tests_case_study_id_idx ON case_tests(case_study_id);",
                "CREATE INDEX IF NOT EXISTS case_tests_lab_type_idx ON case_tests(lab_type);",
                "CREATE INDEX IF NOT EXISTS case_tests_case_lab_type_idx ON case_tests(case_study_id, lab_type);",
                
                # Indexes برای user_progress
                "CREATE INDEX IF NOT EXISTS user_progre_user_id_77f83f_idx ON user_progress(user_id);",
                "CREATE INDEX IF NOT EXISTS user_progre_case_study_id_idx ON user_progress(case_study_id);",
                "CREATE INDEX IF NOT EXISTS user_progre_complet_9918bf_idx ON user_progress(completed);",
                "CREATE INDEX IF NOT EXISTS user_progre_user_id_2c0065_idx ON user_progress(user_id, completed);",
                "CREATE INDEX IF NOT EXISTS user_progre_complet_a63705_idx ON user_progress(completed_at);",
                "CREATE INDEX IF NOT EXISTS user_progre_user_id_437e98_idx ON user_progress(user_id, case_study_id);",
            ],
            # Reverse SQL برای حذف indexes (در صورت rollback)
            reverse_sql=[
                "DROP INDEX IF EXISTS courses_boo_user_id_847f49_idx;",
                "DROP INDEX IF EXISTS courses_boo_case_id_e29590_idx;",
                "DROP INDEX IF EXISTS courses_boo_user_id_7a6f1b_idx;",
                "DROP INDEX IF EXISTS courses_cas_is_publ_74fbc8_idx;",
                "DROP INDEX IF EXISTS courses_cas_categor_460f02_idx;",
                "DROP INDEX IF EXISTS courses_cas_sub_cat_230bd9_idx;",
                "DROP INDEX IF EXISTS courses_cas_created_d57339_idx;",
                "DROP INDEX IF EXISTS courses_sli_case_id_69ce3c_idx;",
                "DROP INDEX IF EXISTS courses_sli_case_id_de36cb_idx;",
                "DROP INDEX IF EXISTS courses_sub_categor_d0e11c_idx;",
                "DROP INDEX IF EXISTS courses_sub_name_a45ac1_idx;",
                "DROP INDEX IF EXISTS case_tests_case_study_id_idx;",
                "DROP INDEX IF EXISTS case_tests_lab_type_idx;",
                "DROP INDEX IF EXISTS case_tests_case_lab_type_idx;",
                "DROP INDEX IF EXISTS user_progre_user_id_77f83f_idx;",
                "DROP INDEX IF EXISTS user_progre_case_study_id_idx;",
                "DROP INDEX IF EXISTS user_progre_complet_9918bf_idx;",
                "DROP INDEX IF EXISTS user_progre_user_id_2c0065_idx;",
                "DROP INDEX IF EXISTS user_progre_complet_a63705_idx;",
                "DROP INDEX IF EXISTS user_progre_user_id_437e98_idx;",
            ],
        ),
    ]
