# Generated by Django 5.2.3 on 2025-10-02 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('monthly', 'ماهانه'), ('quarterly', 'سه ماهه'), ('yearly', 'سالانه'), ('lifetime', 'مادام\u200cالعمر')], default='monthly', max_length=20, verbose_name='نوع اشتراک')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده'), ('pending', 'در انتظار')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='روش پرداخت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه تراکنش')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='تمدید خودکار')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
