# Generated by Django 5.2.3 on 2025-10-12 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('duration_type', models.CharField(choices=[('monthly', 'یک ماهه'), ('quarterly', 'سه ماهه'), ('biannual', 'شش ماهه'), ('yearly', 'یک ساله'), ('lifetime', 'مادام\u200cالعمر')], max_length=20, verbose_name='نوع مدت')),
                ('duration_days', models.IntegerField(verbose_name='تعداد روز')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('features', models.TextField(help_text='ویژگی\u200cها (هر خط یک ویژگی)', verbose_name='ویژگی\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_popular', models.BooleanField(default=False, verbose_name='محبوب')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('manual', 'دستی')], default='zarinpal', max_length=20, verbose_name='درگاه پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'بازگشت داده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('authority', models.CharField(blank=True, max_length=255, null=True, verbose_name='Authority کد')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.subscription', verbose_name='اشتراک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_payme_created_8b0a01_idx'), models.Index(fields=['user', 'status'], name='users_payme_user_id_92394f_idx'), models.Index(fields=['authority'], name='users_payme_authori_b7507a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان افزودن')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.cart', verbose_name='سبد خرید')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscriptionplan', verbose_name='پلن اشتراک')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم\u200cهای سبد خرید',
                'unique_together': {('cart', 'plan')},
            },
        ),
    ]
