# Generated by Django 5.2.3 on 2025-10-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscriptionplan_cart_payment_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد تایید')),
                ('purpose', models.CharField(choices=[('register', 'ثبت\u200cنام'), ('login', 'ورود'), ('password_reset', 'بازیابی رمز عبور')], max_length=20, verbose_name='هدف')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('attempts', models.IntegerField(default=0, verbose_name='تعداد تلاش')),
            ],
            options={
                'verbose_name': 'کد تایید OTP',
                'verbose_name_plural': 'کدهای تایید OTP',
                'db_table': 'otp_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose'], name='otp_verific_phone_n_97f312_idx'), models.Index(fields=['expires_at'], name='otp_verific_expires_e91cd1_idx')],
            },
        ),
    ]
