# Generated by Django 4.2.7 on 2025-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otpverification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='users_carti_cart_id_5ea1de_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['plan'], name='users_carti_plan_id_61435e_idx'),
        ),
    ]
